FROM quay.io/fedora/fedora-bootc:latest

RUN dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm &&\
    dnf5 install 'dnf5-command(copr)' -y && dnf copr enable solopasha/hyprland -y &&\
    dnf install -y \
        hyprland \
        vim \
        htop &&\
    dnf clean all


# -- Finalize container setup --
RUN bootc container lint