version: "3"

tasks:
  containerfile:
    desc: "Generate Containerfile for boot-c"
    vars:
      recipe: '{{.recipe | default "recipe" }}'
    cmds:
      - bluebuild generate ./recipes/{{ .recipe }}.yml -o Containerfile
  oci:
    desc: "Build boot-c oci image"
    vars:
      recipe: '{{.recipe | default "recipe" }}'
    cmds:
      - bluebuild build ./recipes/{{ .recipe }}.yml
  iso:
    desc: "Build boot-c install iso"
    vars:
      recipe: '{{.recipe | default "recipe" }}'
    cmds:
      - bluebuild generate-iso -o output/iso/ --iso-name weebo-os-{{ .recipe }}.iso recipe recipes/{{ .recipe }}.yml
  iso-remote:
    desc: "Build boot-c install iso with remote sources"
    cmds:
      - bluebuild generate-iso -o output/iso/ --iso-name weebo-os-remote.iso image ghcr.io/batleforc/weebo-os
